
version: "3"

services:
  server:
    entrypoint: sh -c "sleep 10 && npm run-script db && npm run-script dev"
    volumes:
      - ./server/src:/app/src
      - ./server/prisma:/app/prisma
    environment:
      STAGE: development
      COOKIES_DOMAIN: '.'

  client:
    stdin_open: true
    environment:
      REACT_APP_API_URL: http://localhost:8081
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public