version: "3"

services:
  server:
    build: ./server
    restart: unless-stopped
    environment:
      PORT: 8081
      CORS: all
      SERVER_GOOGLE_CLIENT_ID: ${SERVER_GOOGLE_CLIENT_ID}
      SERVER_GOOGLE_CLIENT_SECRET: ${SERVER_GOOGLE_CLIENT_SECRET}
      COOKIE_SESSION_SECRET: supersecret
      DATABASE_URL: postgresql://postgres:password@database:5432/hwexporter
      API_URL: http://localhost:8081
      APP_URL: http://localhost:3000
      RATE_LIMIT_REQUEST: 10
    depends_on:
      - database

  client:
    build: ./client
    environment:
      REACT_APP_API_URL: http://localhost:8081

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hwexporter